"""Auto-start on boot support (Windows Registry Run key).

When auto-start is enabled, registers a single PAVP-Proxy entry that starts
the proxy server on boot. The UI is no longer registered separately; instead,
the proxy reads the *auto_start_ui* setting from settings.json and launches
the UI on demand if it is not already running (see proxy_server.run_server).

Approach:
1. If the built exe (dist/pavp/pavp.exe) exists, register it directly
   in the registry Run key. The exe is built with --noconsole (Windows
   GUI subsystem), so no console window appears.
2. Otherwise, fall back to the Python-based launcher (pythonw.exe +
   ~/.pavp/start_proxy.py).
"""
from __future__ import annotations

import sys
from pathlib import Path

_STARTUP_SCRIPT = Path.home() / ".pavp" / "start_proxy.py"


def _find_built_exe() -> Path | None:
    """Look for the PyInstaller-built executable.

    When running as a frozen (PyInstaller) exe, sys.executable points to
    the exe itself - return it directly.
    When running from source, check common build output directories.
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve()

    project_root = Path(__file__).resolve().parent.parent
    candidates = [
        project_root / "build" / "pavp" / "pavp.exe",
        project_root / "dist" / "pavp" / "pavp.exe",
    ]
    for p in candidates:
        if p.exists():
            return p
    return None


def set_auto_start(enabled: bool, port: int | None = None) -> None:
    """Enable or disable auto-start in Windows registry.

    When enabled, registers a single PAVP-Proxy entry that starts the proxy
    server on boot. The UI is launched on demand by the proxy itself (based
    on the *auto_start_ui* setting in settings.json), so a separate PAVP-UI
    registry entry is no longer needed.

    Any legacy PAVP-UI registry entry is always cleaned up.
    """
    if sys.platform != "win32":
        return

    if port is None:
        from .settings import load as _load, DEFAULT_PORT
        try:
            port = _load().get("proxy_port", DEFAULT_PORT)
        except Exception:
            port = DEFAULT_PORT

    import winreg

    key_path = r"Software\Microsoft\Windows\CurrentVersion\Run"
    key = winreg.OpenKey(
        winreg.HKEY_CURRENT_USER,
        key_path,
        0,
        winreg.KEY_SET_VALUE | winreg.KEY_QUERY_VALUE,
    )
    try:
        if enabled:
            built_exe = _find_built_exe()
            project_root = str(Path(__file__).resolve().parent.parent)

            if built_exe:
                # --- Direct exe registration ---
                # The exe is built with --noconsole (Windows GUI subsystem),
                # so no console window appears when launched via the
                # registry Run key at boot.
                proxy_cmd = f'"{built_exe}" --headless'
                winreg.SetValueEx(key, "PAVP-Proxy", 0, winreg.REG_SZ, proxy_cmd)
            else:
                # --- Fall back to Python-based launcher ---
                python_dir = Path(sys.executable).parent
                pythonw = str(python_dir / "pythonw.exe")
                if not Path(pythonw).exists():
                    pythonw = sys.executable  # fallback

                python_exe = str(python_dir / "python.exe")

                # Write (or refresh) the launcher script
                _write_startup_script(project_root, python_exe)

                # Registry: pythonw.exe runs the launcher - zero window flash.
                proxy_cmd = f'"{pythonw}" "{_STARTUP_SCRIPT}"'
                winreg.SetValueEx(key, "PAVP-Proxy", 0, winreg.REG_SZ, proxy_cmd)

            # Always clean up the legacy PAVP-UI entry (no longer used).
            try:
                winreg.DeleteValue(key, "PAVP-UI")
            except FileNotFoundError:
                pass
        else:
            # Remove both entries when auto-start is disabled
            for name in ("PAVP-Proxy", "PAVP-UI"):
                try:
                    winreg.DeleteValue(key, name)
                except FileNotFoundError:
                    pass
    finally:
        winreg.CloseKey(key)


def _write_startup_script(project_root: str, python_exe: str) -> None:
    """Write (or refresh) the proxy launcher script into ~/.pavp/.

    The script:
    1. Waits for network readiness.
    2. Spawns the proxy (auto-increments if the configured port is occupied).
    3. Waits for the proxy health endpoint to respond.
    4. Writes a startup status log for diagnostics.
    """
    _STARTUP_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    _STARTUP_SCRIPT.write_text(
        f'''"""PAVP proxy launcher - triggered by Windows registry Run key.

This script is auto-generated by pavp.auto_start.set_auto_start().
It is run by pythonw.exe to avoid any console window flash.
"""
import subprocess, sys, os, time, socket, json
from pathlib import Path

PROJECT_ROOT = {project_root!r}
PYTHON_EXE   = {python_exe!r}
LOG_DIR      = Path(PROJECT_ROOT) / "log"
BOOT_LOG     = Path.home() / ".pavp" / "boot.log"
SETTINGS     = Path.home() / ".pavp" / "settings.json"

# ------------------------------------------------------------------
# 1. Boot log helpers
# ------------------------------------------------------------------
BOOT_LOG.parent.mkdir(parents=True, exist_ok=True)
def _log(msg: str):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(BOOT_LOG, "a", encoding="utf-8") as f:
        f.write(f"[{{timestamp}}] {{msg}}\\n")

def _read_proxy_port() -> int:
    """Read the actual port the proxy chose (from settings.json)."""
    try:
        data = json.loads(SETTINGS.read_text(encoding="utf-8-sig"))
        return data.get("proxy_port", 5401)
    except Exception:
        return 5401

try:
    _log("Boot launcher started")

    # ------------------------------------------------------------------
    # 2. Wait for network (up to 60s after boot)
    # ------------------------------------------------------------------
    NETWORK_TIMEOUT = 60
    _log(f"Waiting for network (timeout={{NETWORK_TIMEOUT}}s)...")
    deadline = time.time() + NETWORK_TIMEOUT
    net_ok = False
    while time.time() < deadline:
        try:
            socket.create_connection(("8.8.8.8", 53), timeout=3).close()
            net_ok = True
            break
        except OSError:
            time.sleep(2)
    if net_ok:
        _log("Network is ready")
    else:
        _log("WARNING: Network not ready after timeout, starting proxy anyway")

    # ------------------------------------------------------------------
    # 3. Spawn proxy process - fully detached
    #    No --port given; proxy reads the port from settings.json and
    #    auto-increments if it is occupied.
    # ------------------------------------------------------------------
    os.chdir(PROJECT_ROOT)
    sys.path.insert(0, PROJECT_ROOT)

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = open(LOG_DIR / "pavp_proxy.log", "w")

    DETACHED_PROCESS = 0x00000008
    CREATE_NO_WINDOW = 0x08000000
    creationflags = DETACHED_PROCESS | CREATE_NO_WINDOW

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    proc = subprocess.Popen(
        [PYTHON_EXE, "-m", "pavp.proxy_server",
         "--host", "0.0.0.0"],
        stdout=log_file,
        stderr=subprocess.STDOUT,
        cwd=PROJECT_ROOT,
        env=env,
        creationflags=creationflags,
    )
    _log(f"Proxy spawned (pid={{proc.pid}})")

    # ------------------------------------------------------------------
    # 4. Wait for proxy health endpoint (up to 30s)
    #    Read the actual port from settings.json (proxy updates it).
    # ------------------------------------------------------------------
    import urllib.request
    HEALTH_TIMEOUT = 30
    deadline = time.time() + HEALTH_TIMEOUT
    health_ok = False
    while time.time() < deadline:
        time.sleep(1)
        if proc.poll() is not None:
            _log(f"ERROR: Proxy exited early with code {{proc.returncode}}")
            break
        actual_port = _read_proxy_port()
        try:
            r = urllib.request.urlopen(
                f"http://127.0.0.1:{{actual_port}}/health", timeout=2)
            if r.status == 200:
                health_ok = True
                _log(f"Proxy health check passed on port {{actual_port}}")
                break
        except Exception:
            continue

    if not health_ok:
        _log("WARNING: Proxy health check did not pass")

except Exception as e:
    _log(f"FATAL: {{type(e).__name__}}: {{e}}")
    import traceback
    _log(traceback.format_exc())
''',
        encoding="utf-8",
    )